stages:
  - test
  - deploy

test:
  stage: test
  script:
    - docker build --rm -t django_app .
    - docker run -p 8000:8000 django_app

deploy:
  stage: deploy
  script:
    - echo "Deploying..."