stages:
  - test
  - deploy

test:
  stage: test
  script:
    - pip install pipenv
    - pipenv install --system --deploy
    - cd Library
    - pytest

deploy:
  stage: deploy
  script:
    - echo "Deploying..."